"""Make car_id nullable in service_appointment

Revision ID: 321763c665ca
Revises: 85b41b453c83
Create Date: 2024-06-29 20:51:42.157387

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '321763c665ca'
down_revision = '85b41b453c83'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_appointment', schema=None) as batch_op:
        batch_op.alter_column('car_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_appointment', schema=None) as batch_op:
        batch_op.alter_column('car_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
